/* eslint-disable @next/next/no-page-custom-font */
import Head from "next/head";

import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';

import "./globals.css";
import { MainLayout } from "@/layouts";
import { ReduxProvider } from "@/redux/provider";
import { settingApi } from "@/services";
import { getLocale } from "@/helpers/utils/server";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = (await getLocale()) || "vi";
  const setting = await settingApi.getSetting(locale);

  const store = {
    locale,
    setting,
  };
  return (
    <html lang="en">
      <Head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
        <meta name="viewport" content="width=device-width,initial-scale=1" />
      </Head>
      <body>
        <ReduxProvider data={store}>
          <MainLayout>{children}</MainLayout>
        </ReduxProvider>
      </body>
    </html>
  );
}
